"""Orchestrate the review: fetch diff -> fan out agents -> judge -> post comment."""
from __future__ import annotations

import os
from typing import Any

from .agents import run_all_agents
from .github_client import GitHubClient
from .judge import run_judge

VERDICT_LABELS = {
    "approve": "Approved",
    "comment": "Comments",
    "request_changes": "Changes requested",
}

MAX_DIFF_CHARS = int(os.environ.get("REVIEWER_MAX_DIFF_CHARS", "200000"))
DIFF_TRUNCATION_NOTICE = (
    "\n\n[... diff truncated by reviewer — exceeded "
    f"{MAX_DIFF_CHARS} chars. Set REVIEWER_MAX_DIFF_CHARS to raise the limit. ...]\n"
)


def _maybe_truncate(diff: str) -> tuple[str, bool]:
    if len(diff) <= MAX_DIFF_CHARS:
        return diff, False
    return diff[:MAX_DIFF_CHARS] + DIFF_TRUNCATION_NOTICE, True


def _format_finding(f: dict) -> str:
    loc = f["file"] + (f":{f['line']}" if f["line"] is not None else "")
    flagged = ", ".join(f["flagged_by"])
    return (
        f"- **{f['title']}** — `{loc}`  \n"
        f"  {f['details']}  \n"
        f"  _Suggestion:_ {f['suggestion']}  \n"
        f"  _Flagged by:_ {flagged}"
    )


def _format_bucket(title: str, items: list[dict]) -> str:
    if not items:
        return ""
    body = "\n".join(_format_finding(f) for f in items)
    return f"### {title}\n\n{body}\n"


def format_comment(verdict: dict, agent_results: list[dict]) -> str:
    label = VERDICT_LABELS.get(verdict["verdict"], verdict["verdict"])

    parts = [
        "## Multi-Agent Code Review",
        "",
        f"**Verdict:** {label}",
        "",
        verdict["summary"],
        "",
    ]
    parts.append(_format_bucket("Must fix", verdict["must_fix"]))
    parts.append(_format_bucket("Should fix", verdict["should_fix"]))
    parts.append(_format_bucket("Consider", verdict["consider"]))

    cache_read = sum(r["usage"]["cache_read_input_tokens"] for r in agent_results)
    cache_write = sum(r["usage"]["cache_creation_input_tokens"] for r in agent_results)
    total_in = sum(r["usage"]["input_tokens"] for r in agent_results)
    total_out = sum(r["usage"]["output_tokens"] for r in agent_results)

    parts.append("<details><summary>Run details</summary>\n")
    parts.append(
        f"- Reviewers: {', '.join(r['name'] for r in agent_results)}\n"
        f"- Reviewer tokens: in={total_in}, out={total_out}, "
        f"cache_write={cache_write}, cache_read={cache_read}\n"
        f"- Judge tokens: in={verdict['_usage']['input_tokens']}, "
        f"out={verdict['_usage']['output_tokens']}"
    )
    parts.append("\n</details>")
    parts.append("\n<sub>Generated by multi-agent-pr-reviewer</sub>")
    return "\n".join(p for p in parts if p)


async def review_pr(
    repo: str, pr_number: int, *, dry_run: bool = False
) -> dict[str, Any]:
    github_token = os.environ.get("GITHUB_TOKEN")
    if not github_token:
        raise RuntimeError("GITHUB_TOKEN env var is required")

    async with GitHubClient(token=github_token, repo=repo) as gh:
        diff = await gh.get_pr_diff(pr_number)
        diff, truncated = _maybe_truncate(diff)

        agent_results = await run_all_agents(diff)
        verdict = await run_judge(agent_results)
        comment = format_comment(verdict, agent_results)

        if dry_run:
            print(comment)
        else:
            await gh.post_comment(pr_number, comment)

    return {
        "verdict": verdict["verdict"],
        "comment": comment,
        "agent_results": agent_results,
    }
